-   id: check-file-names
    name: Check files for non-compliant names
    description: This hook ensures that filenames by default only consist of lowercase and uppercase characters and dashes.
    entry: check-file-names.py
    language: script
    types: [file]
    exclude: ^\.|README|Readme.*$
-   id: check-vault-files
    name: Check for files encrypted with ansible-vault
    description: This hook ensures that files with 'vault' in filename are encrypted with ansible-vault.
    entry: check-vault-encryption.py
    language: script
    types: [file]
    files: '^.*vault.*$'
